second commit
ChabVlad/BookStore pull request #1
Opened 2024-09-04 13:49 UTC by ChabVlad

2024-09-04 13:57 UTC, Elena-Bruyako requested changes
see comments

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/model/Book.java
> +@Table(name = "names")
```suggestion
@Table(name = "books")
```

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/model/Book.java
> +@Data
```suggestion
@Getter
@Setter
```

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/model/Book.java
> +    private Long price;
```suggestion
    private BigDecimal price;
```

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/repository/impl/BookRepositoryImpl.java
> +        return null;
you should implement this method

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/repository/impl/BookRepositoryImpl.java
> +        return List.of();
same

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/service/BookService.java
> +@Service
```suggestion
```

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/service/impl/BookServiceImpl.java
> +public class BookServiceImpl implements BookService {
```suggestion
@Service
public class BookServiceImpl implements BookService {
```

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/service/impl/BookServiceImpl.java
> +        return null;
implement this method

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/service/impl/BookServiceImpl.java
> +        return List.of();
implement this method

2024-09-04 13:57 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
h2 is used for test purpose, create mysql database

2024-09-05 11:05 UTC, okuzan approved these changes

2024-09-05 11:05 UTC, okuzan commented on src/main/java/project/bookstore/BookStoreApplication.java
> +
```suggestion
    public static void main(String[] args) {
        SpringApplication.run(BookStoreApplication.class, args);
    }
```

2024-09-05 11:05 UTC, okuzan commented on pom.xml
> +
```suggestion
```

2024-09-06 10:45 UTC, closed without merging