Spring security
ChabVlad/BookStore pull request #10
Opened 2024-09-19 14:38 UTC by ChabVlad

2024-09-20 08:14 UTC, ahoienko requested changes
Good job! left minor comments

2024-09-20 08:14 UTC, ahoienko commented on src/main/java/project/bookstore/controller/BookController.java
> +//@PreAuthorize("hasAnyRole('ROLE_ADMIN', 'ROLE_USER')")
Please don`t push commented code on remote

2024-09-20 08:14 UTC, ahoienko commented on src/main/resources/application.properties
> +spring.datasource.password=!Vladius080197
It is unsafe to push passwords on git, you should left this field blank or use env variable

2024-09-20 08:14 UTC, ahoienko commented on src/main/java/project/bookstore/service/impl/UserServiceImpl.java
> +        Role role = roleRepo.findByRole(RoleName.ROLE_ADMIN);
Why any user that registers is admin?

2024-09-21 07:57 UTC, liliia-ponomarenko requested changes
Good job! Let's improve your solution ;)

2024-09-21 07:57 UTC, liliia-ponomarenko commented on src/main/java/project/bookstore/model/User.java
> +public class User implements UserDetails {
It is better to override all methods with UserDetails. In particular, the isEnabled method will have its own implementation in your solution ;)

2024-09-21 07:57 UTC, liliia-ponomarenko commented on src/main/java/project/bookstore/repository/role/RoleRepo.java
> +public interface RoleRepo extends JpaRepository<Role, Integer> {
```suggestion
public interface RoleRepository extends JpaRepository<Role, Long> {
```
Don't use abbreviations in the names of variables, classes, and methods.
Also, you used Long as an id variable type.

2024-09-21 07:57 UTC, liliia-ponomarenko commented on src/main/java/project/bookstore/repository/user/UserRepo.java
> +public interface UserRepo extends JpaRepository<User, Long> {
```suggestion
public interface UserRepository extends JpaRepository<User, Long> {
```

2024-09-21 07:57 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/06-add-isDeleted-to-users.yaml
> +                    nullable: false
Left one empty line at the end of the file  ;)

2024-09-22 17:17 UTC, Elena-Bruyako requested changes
one comment

2024-09-22 17:17 UTC, Elena-Bruyako commented on src/main/java/project/bookstore/config/SecurityConfig.java
> +                                        HttpMethod.POST,
```suggestion
```

2024-09-23 06:45 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-09-23 11:04 UTC, merged