Create tests
ChabVlad/BookStore pull request #17
Opened 2024-10-08 19:28 UTC by ChabVlad

2024-10-10 06:19 UTC, liliia-ponomarenko requested changes
Good job! Let's improve your solution and answer the question ;)

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/controller/BookControllerTest.java
> +        tearDown(dataSource);
Why do you need to call tearDown in beforeEach if you already called it in atrerEach method?

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/controller/BookControllerTest.java
> +        expected.setCategories(Set.of(new Category()));
I see the same code in the previous method. You can move it to the private method and reuse ;)

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/controller/CategoryControllerTest.java
> +        tearDown(dataSource);
the same

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/controller/CategoryControllerTest.java
> +    }
you can move it to the private method and use only one BeforeEach method

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/controller/CategoryControllerTest.java
> +                .andExpect(status().isOk())
you can use status CREATED for this controller (and other similar methods)

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/service/BookServiceTest.java
> +                .when(bookMapper).toModel(requestDto);
do you have such logic in your mapper?  I can't find it. So, what are you testing here?

2024-10-10 06:19 UTC, liliia-ponomarenko commented on src/test/java/project/bookstore/service/BookServiceTest.java
> +        })
why do you need it?

2024-10-11 16:18 UTC, ahoienko approved these changes
Good job!

2024-10-11 16:18 UTC, ahoienko commented on src/test/java/project/bookstore/controller/BookControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
Please use static import

2024-10-11 16:39 UTC, merged